---
version: "3.9"

services:
  tor:
    image: "bushidomarket/tor:${BM_VERSION_TAG}"
    container_name: tor-proxy
    build: 
      context: .
      dockerfile: "./etc/tor/Dockerfile"
    environment:
      TOR_PROXY_ACCEPT: ${TOR_PROXY_ACCEPT}
    volumes:
      - tor:/tor/
    restart: unless-stopped
    # We do not need to expose any port because all the request are going
    # inside of the container network
    networks:
      tor-net:
        ipv4_address: ${TOR_STATIC_IP}
  web_server:
    image: "bushidomarket/webserver:${BM_VERSION_TAG}"
    container_name: nokyc-api
    build:
      context: .
      dockerfile: 'etc/fastapi/Dockerfile'
    command: "/start-reload.sh"
    volumes:
      - ./src/app:/app/
    ports:
      - "8080:8081"
    networks:
      tor-net:
        ipv4_address: ${APP_STATIC_IP}
volumes:
  tor:
  nokyc-app:
# Create a network to add the nokyc-api IP in the /tor/torrc file
# We cannot add the container name because we get the following error
# Malformed IP "tor-proxy" in address pattern; rejecting.
networks:
  tor-net:
    name: bushido-market-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}